# Generated by Django 2.2.7 on 2019-12-27 13:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='null'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
