# Generated by Django 2.2.7 on 2020-01-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0002_auto_20200105_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=50)),
                ('chapter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=25)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.Exams')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.Subject'),
        ),
    ]
