# Generated by Django 2.2.7 on 2020-01-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0003_auto_20200105_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.Chapter'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.Subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.Topic'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.Exams'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chapter_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OnlineExamination.Chapter'),
        ),
    ]
